version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - bbqq_network
    volumes:
      - /home/quotation6699/nginx.conf:/etc/nginx/nginx.conf
      - bbqq_static:/data/static/
      - bbqq_media:/data/media/
    secrets:
      - NGINX_AUTH

  django:
    image: bbqq_django:5
    networks:
      - bbqq_network
    volumes:
      - bbqq_static:/home/quotation6699/staticfiles/
      - bbqq_media:/home/quotation6699/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - bbqq_network
    volumes:
      - bbqq_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  bbqq_network:

volumes:
  bbqq_static:
  bbqq_media:
  bbqq_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  NGINX_AUTH:
    external: true