version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - jewon1016_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - jewon1016_static:/data/static/
      - jewon1016_media:/data/media/

  django:
    image: jewon1016_django:3
    networks:
      - jewon1016_network
    volumes:
      - jewon1016_static:/home/gis_3ban_1/staticfiles/
      - jewon1016_media:/home/gis_3ban_1/media/

networks:
  jewon1016_network:

volumes:
  jewon1016_static:
  jewon1016_media: