version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - jewon1016_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - jewon1016_static:/data/static/
      - jewon1016_media:/data/media/

  django:
    image: jewon1016_django:5
    networks:
      - jewon1016_network
    volumes:
      - jewon1016_static:/home/gis_3ban_1/staticfiles/
      - jewon1016_media:/home/gis_3ban_1/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - jewon1016_network
    volumes:
      - jewon1016_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  jewon1016_network:

volumes:
  jewon1016_static:
  jewon1016_media:
  jewon1016_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true