# Generated by Django 3.2.4 on 2021-10-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewModel',
        ),
    ]
